FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y wget qemu-utils nbd-client qemu-kvm libvirt-daemon-system libguestfs-tools

RUN mkdir -p /img

RUN wget https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img -O /img/jammy-server-cloudimg-amd64.img && \
    ls -l /img/jammy-server-cloudimg-amd64.img

RUN qemu-img convert -O raw /img/jammy-server-cloudimg-amd64.img /img/jammy-server-cloudimg-amd64.raw
RUN qemu-img resize /img/jammy-server-cloudimg-amd64.raw +4G
RUN mkdir /scripts
RUN mkdir /var/lib/formnet
RUN mkdir /artifacts

COPY ./target/release/form-build-server /bin/form-build-server
COPY ./form-pack/scripts/image-customizer-test.sh /scripts/
COPY ./artifacts/modules /lib/modules
COPY ./artifacts/vmlinuz* /boot/
COPY ./artifacts/formnet-client /var/lib/formnet/formnet

ENTRYPOINT ["/bin/bash"]
