FROM ubuntu:22.04

RUN apt-get update && apt-get upgrade
RUN apt-get install -y protobuf-compiler libprotobuf-dev build-essential \
    clang llvm pkg-config \
    linux-headers-$(uname -r) qemu-kvm libvirt-dev \
    protobuf-compiler libprotobuf-dev libdbus-1-dev \
    libudev-dev libfuse-dev libseccomp-dev \
    libnetfilter-queue-dev libnl-3-dev libnl-route-3-dev \
    zlib1g-dev libbpf-dev liburing-dev libssl-dev

RUN mkdir -p /usr/local/bin
RUN mkdir -p /var/lib/formation/formnet
RUN mkdir -p /var/lib/formation/kernel
RUN mkdir -p /var/lib/formation/netplan
RUN mkdir -p /var/lib/formation/vm-images
RUN mkdir -p /run/form-vm

COPY ./target/release/formnet /usr/local/bin/formnet
COPY ./target/release/formnet-client /usr/local/bin/formnet-client
COPY ./target/release/formnet-server /usr/local/bin/formnet-server
COPY ./target/release/formnet-client /var/lib/formnet/formnet
COPY ./target/release/vmm-service-test /usr/local/bin/vmm-service-test
COPY ./target/release/vmm-service /usr/local/bin/vmm-service
COPY ./target/release/form-broker /usr/local/bin/form-broker
COPY ./scripts/run-vmm-service-test.sh /usr/local/bin/run-vmm-service-test.sh
COPY ./scripts/run-formnet.sh /usr/local/bin/run-formnet.sh
COPY ./scripts/entrypoint.sh /entrypoint.sh

RUN chmod +x /usr/local/bin/run-vmm-service-test.sh
RUN chmod +x /usr/local/bin/run-formnet.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3001
EXPOSE 3002

WORKDIR /app
ENTRYPOINT ["/entrypoint.sh"]
