FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y wget qemu-utils nbd-client qemu-kvm libvirt-daemon-system libguestfs-tools

RUN mkdir -p /img

RUN wget https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img -O /img/jammy-server-cloudimg-amd64.img && \
    ls -l /img/jammy-server-cloudimg-amd64.img

RUN mkdir /scripts
RUN mkdir /var/lib/formnet
RUN mkdir /artifacts

COPY ./form-ubuntu/jammy-server-cloudimg-amd64.raw /img/jammy-server-cloudimg-amd64.raw
COPY ./target/release/form-build-server /bin/form-build-server
COPY ./target/release/formnet /var/lib/formnet/formnet
COPY ./artifacts/modules /lib/modules
COPY ./artifacts/vmlinuz* /boot/

ENTRYPOINT ["/bin/bash"]
